# This is the OpenAPI specification for your service. It is used to generate the client code.
# To generate the server code, use the Gradle task `openApiGenerate`. The
# generated code will be placed in `build/generate-resources/main`.
#
# We will evaluate you based on how well you design your API.
# 1. How well it follows REST principles.
# 2. How easy it is to understand and use.
#
# References
# 1. https://swagger.io/specification/
openapi: "3.0.0"
info:
  version: 1.0.0
  title: User Service
  license:
    name: MIT
servers:
  - url: http://localhost
paths:
  /estate:
    post:
      summary: Insert Estate
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/InsertEstateRequest"
      responses:
        "200":
          description: Success response
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/InsertEstateResponse"
        "400":
          description: Bad request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
  /estate/{uuid}/tree:
    post:
      summary: Insert Tree for Estate
      parameters:
        - name: uuid
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/InsertNewTreeRequest"
      responses:
        "200":
          description: Success response
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/InsertNewTreeResponse"
        "400":
          description: Bad request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
  /estate/{uuid}/stats:
    get:
      summary: Get Estate Stats
      parameters:
        - name: uuid
          in: path
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Success response
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/EstateStats"
        "404":
          description: Not found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
  /estate/{uuid}/drone-plan:
    get:
      summary: Get Drone Plan for Estate
      parameters:
        - name: uuid
          in: path
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Success response
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/EstateDronePlanResponse"
        "404":
          description: Not found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
components:
  schemas:
    EstateDB:
      type: object
      properties:
        id:
          type: integer
          format: int64
        uuid:
          type: string
        width:
          type: integer
          format: int32
        length:
          type: integer
          format: int32
      required:
        - uuid
        - width
        - length
    InsertEstateResponse:
      type: object
      properties:
        id:
          type: string
      required:
        - id
    InsertEstateRequest:
      type: object
      properties:
        width:
          type: integer
          format: int32
        length:
          type: integer
          format: int32
      required:
        - width
        - length
    InsertNewTreeRequest:
      type: object
      properties:
        x:
          type: integer
          format: int32
        y:
          type: integer
          format: int32
        height:
          type: integer
        uuid_mst_estate:
          type: string
      required:
        - x
        - y
        - height
        - uuid_mst_estate
    InsertNewTreeResponse:
      type: object
      properties:
        id:
          type: string
      required:
        - id
    EstateStats:
      type: object
      properties:
        count:
          type: integer
          format: int16
        max:
          type: integer
        min:
          type: integer
        median:
          type: integer
    EstateDronePlanResponse:
      type: object
      properties:
        distance:
          type: integer
          format: int32
    ErrorResponse:
      type: object
      properties:
        message:
          type: string
      required:
        - message
